#!/usr/bin/env python

"""
Randomly places molecules in space with a certain density, Boltzmann distribution and computes the scattering in the concentrated limit.
This method does not use cython-made c wrappers, instead it relies on numpy and will therefore have horrible memory mangement. BEWARE if you are trying to simulate a big system, as you might not have enough RAM!
This method does not compute exact atomic form factors but instead approximates each atoms form factor as that of nitrogen.
"""

from odin.scatter import atomic_formfactor as AF
from odin.utils import odinparser
from odin.xray import _q_grid_as_xyz as QXYZ
from odin.xray import Beam,Rings
import numpy as np
from odin.structure import rand_rotate_molecule2, load_coor, remove_COM


def locate(xyz, num_replicas, density):
    """
    Take a structure and generate a system of many conformations, such that they
    are randomly distributed & rotated in space with a given `density`.
    
    This function is useful for approximating a subset of a homogenous solution,
    gas, slurry, etc. composed of the structures indicated by `xyz`.
    
    Parameters
    ----------
    xyz : np.array, float
        atomic positions of sample; shape =  ( num_atoms, 3).
    
    num_replicas : int
        The total number of molecules to include in the system. The total volume
        of the system depends on this parameter and `density`.
        
    density : float
        The number density of species, MICROMOLAR UNITS. That is, umol/L. (This
        software was written by a chemist!).
    
    Returns
    -------
    centers_of_mass : np.array
        The center of masses of each placed structure.
    """
#   determine the box size
    boxvol  = (num_replicas * 1.0e24) / (density * 6.02e17) # in nm^3
    boxsize = np.power(boxvol, 1/3.)            # one dim of a cubic box, in Angstrom

    max_radius = np.max( np.sqrt( np.sum(np.power(xyz , 2), axis=1) ) )
    if boxsize < max_radius*2:
        raise ValueError('You solution is too concentrated for its constituent'
                         ' matter! There is no way it will fit. Box: '
                         '%f, Biggest Molecule: %f' % (boxsize, np.max(max_radius)))
        
    centers_of_mass = np.zeros((num_replicas, 3)) # to store these and use later
    centers_of_mass[0] = np.random.uniform(low=0, high=boxsize, size=3)

    for i in xrange(1, num_replicas ):
        molecule_overlapping = True # initial cond.
        
        attempt = 0
        while molecule_overlapping:
            
            attempt += 1
        
            # suggest a random translation
            centers_of_mass[i] = np.random.uniform(low=0, high=boxsize, size=3)
            
            # check to see if we're overlapping another molecule already placed
            for j in xrange(i):
                molec_dist = np.linalg.norm(centers_of_mass[i] - centers_of_mass[j])
                min_allowable_dist = 2 * max_radius
                
                if molec_dist > min_allowable_dist:
                    # if not, move the molecule there and do a rotation.
                    molecule_overlapping = False
                else:
                    molecule_overlapping = True
                    break
                    
            if attempt > 10000:
                raise RuntimeError('Number of attempts > 10000, density is too high.')
        print "placed molecule, took", attempt, "attempts." 

    return centers_of_mass

def place(xyz, location):
    xyz2 = rand_rotate_molecule2(xyz)
    for x in xrange(3):
        xyz2[:,x] += location[x]
    return xyz2

def vacancies( xyz, perc_mean = 0, perc_var = None) :
    """
    Add atom vacancies to structures, mainly used in 
    nano particle simulations
    
    Parameters
    ----------
    xyz : np.array, float
        atomic positions of sample; shape =  ( num_atoms, 3).
    
    perc_mean : float
        Percentage of vacant atoms

    perc_var : float
        The actual percentage of vacant atoms will be based on
        gaussian random number with 'center = perc_mean' and 
        'width = per_var'

    Returns
    -------
    None : void
    """

    if perc_mean == 0:
        return xyz

    if perc_var == None:
        perc_var = perc_mean/2.
    num_atoms = xyz.shape[0]
    num_vac   = np.random.normal( perc_mean * num_atoms, perc_var * num_atoms  )
    if num_vac > 0 and num_vac < num_atoms:
#       determine vacancy locations
        np.random.seed()
        num_vac        =  int ( num_vac ) 
        new_atom_inds  =  np.random.permutation( num_atoms ) [ 0 : num_atoms - num_vac]
#       remove the vacant atoms
        new_xyz        =  xyz[ new_atom_inds ]

        return new_xyz

    elif num_vac <= 0 :
        return xyz
        
    else :
        raise ValueError('The number of vacancies is greater than the number of atoms. \
                        Consider lowering the perc_mean and perc_var.') 

def main(num_shot, traj, num_mol, dens, energy, qs, num_phi, vac, outfile, dilute=True ):
    
    traj        = remove_COM( traj )

    xyz = traj.xyz[0]  # IN NANOMETERS!!

    #atom_numbs  = np.array([ a.element.atomic_number for a in traj.topology.atoms() ])
 
    #atom_numbs = np.unique(atom_numb)

    #n_atom_type = len( atom_numbs ) 

    #for i in xrange( ):

    #atom_keys = map ( lambda x: str( x ) , list (atom_numbs ) )

    #D = dict (  [ (atom_numbs[i], FF[i]) for i in xrange( len( atom_numbs) ]  )

    intens = np.zeros( (num_shot, qs.shape[0], num_phi) )

    qs       = np.array( qs )
    num_q    = qs.shape[0]
    num_atom = xyz.shape[0]
    qvec     = QXYZ(  qs, num_phi, Beam(-1,energy=energy).k ).reshape( (num_q, num_phi, 3 )  )
    
    FF = np.zeros( num_q, dtype=np.complex128 )
    for i_q in xrange( num_q ) :
#       approx with nitrogen
        FF[i_q] =  AF( 79, qs[i_q] ).astype(np.complex128)

    if dilute:
        for i_shot in xrange( num_shot ) :
            print "computing shot number",i_shot
            scatter    = np.zeros( ( num_q, num_phi)  )
            xyzs  = ( place( xyz, np.zeros(3) )  for i_mol in xrange(num_mol)  )
            for i_mol in xrange( num_mol ):
                xyz_next   = xyzs.next() * 10 # CONVERTING TO ANGSTROMS!!!!!!!!!! 
                xyz_next   = vacancies( xyz_next , vac )
                scatter += np.abs( amplitudes( qvec, xyz_next, FF, num_q, num_phi) ) **2
            intens[i_shot] =  scatter 
        r = Rings (qs, intens, Beam(-1,energy=energy).k )
        r.save( 'dilu-'+outfile)

    else:
        for i_shot in xrange( num_shot ) :
            amps    = np.zeros( ( num_q, num_phi) , dtype=np.complex128 )
            print "computing shot number",i_shot
            COM     = locate( xyz, num_mol, dens )
            xyzs  = ( place( xyz, COM[i_mol] )  for i_mol in xrange(num_mol)  )
            for i_mol in xrange( num_mol ):
                xyz_next   = xyzs.next() * 10 # ANGSTROMS !!!!!!
                xyz_next   = vacancies( xyz_next , vac ) 
                amps += amplitudes( qvec, xyz_next, FF, num_q, num_phi)
            intens[i_shot] =  np.abs( amps ) **2 
        r = Rings (qs, intens, Beam(-1,energy=energy).k )
        r.save( 'conc-'+outfile)

def amplitudes( qvec,  xyz , FF,num_q,num_phi):
    """
    Calculates scattering amplitudes

    Parameters
    ----------
    enery : float
        energy in keV of the xray beam.

    qs : np.array, float
        a list of q values specifying which rings to simulate 
        onto ( inverse angstroms).

    num_phi : int
        number of polar pixels around each ring.

    xyz : np.array, float
        atomic positions of sample; shape =  ( num_atoms, 3).
    
    Returns
    -------
    amp : np.array, shape( len(qs), num_phi )
        the scattering amplitudes.
    """
    
    amp = np.zeros( (num_q, num_phi), dtype=np.complex128  )
    
    for i_q in xrange( num_q ):
        amps = np.dot( qvec[i_q], xyz.T )
        amps = np.exp(  1j * amps  )
        amps = np.sum( amps, axis = 1 ) # approximates form factor using nitrogen
        amp[i_q,:]  =  FF[i_q] * amps 
    return amp


if __name__ == '__main__':
    
    parser = odinparser('Make a odin .ring file containing the scattering from a system of molecules in the concentrated limit.')
    
    parser.add_argument('-i', '--input', type=str, 
                        help='A .coor file containing the atomic positions of a single molecule.')
    
    parser.add_argument('-n', '--num_mol', type=int, 
                        help='The number of molecules to include in the ensemble.')
    
    parser.add_argument('-m', '--num_shot', type=int, 
                        help='The number of shots/exposures.')
    
    parser.add_argument('-p', '--num_phi', type=int, 
                        help='The number of point pixels around each ring.')
    
    parser.add_argument('-d', '--density', type=float, 
                        help='The ensemble density, in micromolar.')
    
    parser.add_argument('-e', '--energy', type=float, 
                        help='The energy of the beam in keV.')
    
    parser.add_argument('-q', '--qfile', type=str, 
                        help='The name of a file containing the q_values (1 per line, in inverse angstroms ).')
    
    parser.add_argument('-v', '--vacancies', default=0, type=float,  
                        help='Fraction of total atoms that are vacant.')
    
    parser.add_argument('-o', '--output', default=None,
                        help='ring file to write output to.')
    
    parser.add_argument('-c', '--concentrate',
                        help='Compute simulations in the concentrated limit.')

    args = parser.parse_args()
    
    if args.input.endswith('.coor') or args.input.endswith('.xyz'):
        input_traj = load_coor( args.input) # loads xyz in nm
    else:
        raise ValueError('input file must be .coor' )

    if args.num_mol == None:
        raise ValueError('Pass a number of molecules using -n.')

    if type(args.num_mol) != np.int:
        raise ValueError( '-n option: number of molecules must be type int.' )
   
    if args.num_shot == None:
        raise ValueError('Pass a number of shots/exposures using -m.')
    
    if type(args.num_shot) != np.int:
        raise ValueError( '-m option: number of shots must be type int.' )
   
    if args.num_phi == None:
        raise ValueError('Pass a number of pixels per ring using -p.')
   
    if type(args.num_phi) != np.int:
        raise ValueError( '-p option: number of ring pixels must be type int.' )
    
    if args.density == None:
        raise ValueError('Pass a density in micro molar using -d.')
   
    if args.energy == None:
        raise ValueError('Pass a energy in angstrom using -e')
   
    if args.qfile == None:
        raise ValueError('Pass a name for a file containing q values (in inverse angstroms) using -q')
    
    if args.concentrate:
        dilu = False
    else:
        dilu = True

    qs = np.loadtxt(args.qfile, ndmin=1)
   
    if args.output == None:
        outfile  = map( lambda x:str(x), [args.num_shot,'sh', args.num_mol,'m', args.density,'d', args.energy,'w', args.num_phi,'ph'] + list(qs) + ['q'] + [args.input]  )
        outfile  = '-'.join( outfile ) + '.ring'
    else:
        outfile  = args.output
    
    main( args.num_shot, input_traj, args.num_mol, args.density, args.energy, qs, args.num_phi,  args.vacancies, outfile, dilu)


